version: '3'
services:
  hub:
    image: selenium/hub:4.3.0-20220726
    container_name: selenium-hub
    ports:
      - 4442-4444:4442-4444
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:4.3.0-20220726
    container_name: node-chrome
    environment:
      - SE_EVENT_BUS_HOST=[IP]
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://[IP]:4444
    shm_size: "2g"
    depends_on:
      - hub
    networks:
      - selenium-grid
  
  edge:
      image: selenium/node-edge:4.3.0-20220726
      container_name: node-edge
      environment:
        - SE_EVENT_BUS_HOST=[IP]
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        - SE_NODE_GRID_URL=http://[IP]:4444
      shm_size: "2g"
      depends_on:
        - hub
      networks:
        - selenium-grid

networks:
  selenium-grid:
    external: false
    name: selenium-grid
